### ISSUE TITLE
File rotation in the fast-logger package does not work on Windows

### ISSUE THREAD

**Issue by seinokatsuhiro** [kazu-yamamoto/easy-file#4]
On Windows, fast-logger opens a log file calling `createFile` with `fILE_APPEND_DATA` mode.
When rotating files, check file size using `System.EasyFile.getFileSize`.
The `getFileSize` opens the file with `gENERIC_READ` and `fILE_SHARE_READ` flags.
It seems that `getFileSize` always throws an permission-denied exception.

API document <https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx>
says 

> If this (FILE_SHARE_WRITE) flag is not specified, but the file or device has been opened for write access or has a file mapping with write access, the function fails.

I think an exception is thrown because `fILE_APPEND_DATA` is write access and `fILE_SHARE_WRITE` flag is not specified.

And the document also says

> If this parameter (dwDesiredAccess) is zero, the application can query certain metadata such as file, directory, or device attributes without accessing that file or device ...

we can write

```
createFile file 0 fILE_SHARE_READ Nothing
  oPEN_EXISTING fILE_ATTRIBUTE_NORMAL Nothing
```

instead of

```
createFile file gENERIC_READ fILE_SHARE_READ Nothing
  oPEN_EXISTING fILE_ATTRIBUTE_NORMAL Nothing
```

I checked the behavior using the following code.

``` .hs
import Control.Exception (SomeException (..), bracket, handle)
import Data.Bits ((.|.))
import Data.Word (Word64)
import Text.Printf (printf)
import System.Win32.File

test :: FilePath -> IO ()
test file = mapM_ printSize modeShares where

  printSize :: (AccessMode, ShareMode) -> IO ()
  printSize (mode, share) = handle
    (\(SomeException e) ->
      printf "Mode = %d, DWR = %03b, Error\n" mode share) $
    bracket open close $ \_ -> do
      size <- getFileSizeWith mode share file
      printf "Mode = %d, DWR = %03b, Size = %d\n" mode share size

  modeShares :: [(AccessMode, ShareMode)]
  modeShares = [ (mode, share) | mode <- [0, gENERIC_READ]
                               , share <- [0 .. 7]]

  -- open like openFileFD in System.Log.FastLogger.FileIO
  open  = createFile file fILE_APPEND_DATA (fILE_SHARE_READ .|. fILE_SHARE_DELETE)
            Nothing oPEN_ALWAYS fILE_ATTRIBUTE_NORMAL Nothing
  close = closeHandle

-- Win32 version getFileSize with given access and share mode.
getFileSizeWith :: AccessMode -> ShareMode -> FilePath -> IO Word64
getFileSizeWith mode share file = bracket setup teardown body
  where
    setup = createFile file mode share Nothing oPEN_EXISTING fILE_ATTRIBUTE_NORMAL Nothing
    teardown = closeHandle
    body fh = fromIntegral . bhfiSize <$> getFileInformationByHandle fh
```

In GHCi

```
> test "foo.log"
Mode = 0, DWR = 000, Size = 322
Mode = 0, DWR = 001, Size = 322
Mode = 0, DWR = 010, Size = 322
Mode = 0, DWR = 011, Size = 322
Mode = 0, DWR = 100, Size = 322
Mode = 0, DWR = 101, Size = 322
Mode = 0, DWR = 110, Size = 322
Mode = 0, DWR = 111, Size = 322
Mode = 2147483648, DWR = 000, Error
Mode = 2147483648, DWR = 001, Error
Mode = 2147483648, DWR = 010, Size = 322
Mode = 2147483648, DWR = 011, Size = 322
Mode = 2147483648, DWR = 100, Error
Mode = 2147483648, DWR = 101, Error
Mode = 2147483648, DWR = 110, Size = 322
Mode = 2147483648, DWR = 111, Size = 322
```

**Comment by kazu-yamamoto** [comment]
@seinokatsuhiro Thank you for this report.
Would you send me a PR?

**Comment by kazu-yamamoto** [comment]
> Usually, there is little need to get the (byte) size of the directory.
> Is it preferable to specify this flag?

Yes, please. I'm not familiar with Windows. So, you should modify the package as you like. :-)

**Comment by seinokatsuhiro** [comment]
Thank you. I will send a PR next week.

**Comment by kazu-yamamoto** [comment]
Ping @seinokatsuhiro

**Comment by seinokatsuhiro** [comment]
Sorry but could you wait a few days?

**Comment by kazu-yamamoto** [comment]
Of course!
